spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fellipecm/argocdhome
    targetRevision: main
stacks:
  - name: kured
  - name: metallb
  # - name: kube-vip
  # - name: ingress-nginx # using traefik that comes with k3s
  - name: longhorn
  - name: kube-prometheus-stack
  # - name: kestra
