kube-vip:

  config:
    address: "192.168.0.250"
  # Check https://kube-vip.io/docs/installation/flags/
  env:
    vip_interface: "eth0"
    vip_arp: "true"
    lb_enable: "true"
    lb_port: "6443"
    vip_cidr: "32"
    cp_enable: "true"
    svc_enable: "true"
    svc_election: "true"
    vip_leaderelection: "false"