{{- range $index, $stack := .Values.stacks }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $stack.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $stack.name }}
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: helm-{{ $stack.name }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
    prune: true
    selfHeal: true
    retry:
    limit: 10
    backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
{{- end }}